### ISSUE TITLE
xpath 

### ISSUE THREAD

**Issue by feijoes** [akhilrajs/bulk-inviter-BOT#2]
[resources](https://github.com/akhilrajs/bulk-inviter-BOT/tree/main/resources)/xpaths you should just make one json file with the xpath, is not necessary 1 .txt file for just 1 xpath

make just xpath.json with:
````
{
    "crop": "/html/body/div[1]/div/div/div[2]/div[2]/span/div/span/div/div/div[2]/div/div[1]/div[1]/div[2]/div[5]/div/span"
     "menu" : "/html/body/div[1]/div/div/div[3]/header/div[2]/div/span/div[3]/div/span"
}

**Comment by akhilrajs** [comment]
the xpaths are in the repository and the program checks it online while excecution . i understand what you meant but i am not well versed in using JSON
